spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
        git:
          uri: https://github.com/Anandkrish4204/config.git
          searchPaths: licensing-service



server:
  port: 8071

encrypt:
  key: secretKey